/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CampaignRouteImport } from './routes/campaign'
import { Route as CapsulesRouteImport } from './routes/capsules'
import { Route as CircleRouteImport } from './routes/circle'
import { Route as DecoyRouteImport } from './routes/decoy'
import { Route as DexterRouteImport } from './routes/dexter'
import { Route as ProtocolRouteImport } from './routes/protocol'
import { Route as TriggersRouteImport } from './routes/triggers'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as CapsulesIndexRouteImport } from './routes/capsules/index'
import { Route as CapsulesIdRouteImport } from './routes/capsules/$id'
import { Route as SessionIndexRouteImport } from './routes/session/index'
import { Route as SessionIdRouteImport } from './routes/session/$id'
import { Route as SessionNewRouteImport } from './routes/session/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignRoute = CampaignRouteImport.update({
  id: '/campaign',
  path: '/campaign',
  getParentRoute: () => rootRouteImport,
} as any)
const CapsulesRoute = CapsulesRouteImport.update({
  id: '/capsules',
  path: '/capsules',
  getParentRoute: () => rootRouteImport,
} as any)
const CircleRoute = CircleRouteImport.update({
  id: '/circle',
  path: '/circle',
  getParentRoute: () => rootRouteImport,
} as any)
const DecoyRoute = DecoyRouteImport.update({
  id: '/decoy',
  path: '/decoy',
  getParentRoute: () => rootRouteImport,
} as any)
const DexterRoute = DexterRouteImport.update({
  id: '/dexter',
  path: '/dexter',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtocolRoute = ProtocolRouteImport.update({
  id: '/protocol',
  path: '/protocol',
  getParentRoute: () => rootRouteImport,
} as any)
const TriggersRoute = TriggersRouteImport.update({
  id: '/triggers',
  path: '/triggers',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const CapsulesIndexRoute = CapsulesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CapsulesRoute,
} as any)
const CapsulesIdRoute = CapsulesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CapsulesRoute,
} as any)
const SessionIndexRoute = SessionIndexRouteImport.update({
  id: '/session/',
  path: '/session/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionIdRoute = SessionIdRouteImport.update({
  id: '/session/$id',
  path: '/session/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionNewRoute = SessionNewRouteImport.update({
  id: '/session/new',
  path: '/session/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/campaign': typeof CampaignRoute
  '/capsules': typeof CapsulesRouteWithChildren
  '/circle': typeof CircleRoute
  '/decoy': typeof DecoyRoute
  '/dexter': typeof DexterRoute
  '/protocol': typeof ProtocolRoute
  '/triggers': typeof TriggersRoute
  '/verify': typeof VerifyRoute
  '/capsules/$id': typeof CapsulesIdRoute
  '/session/$id': typeof SessionIdRoute
  '/session/new': typeof SessionNewRoute
  '/capsules/': typeof CapsulesIndexRoute
  '/session/': typeof SessionIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/campaign': typeof CampaignRoute
  '/circle': typeof CircleRoute
  '/decoy': typeof DecoyRoute
  '/dexter': typeof DexterRoute
  '/protocol': typeof ProtocolRoute
  '/triggers': typeof TriggersRoute
  '/verify': typeof VerifyRoute
  '/capsules/$id': typeof CapsulesIdRoute
  '/session/$id': typeof SessionIdRoute
  '/session/new': typeof SessionNewRoute
  '/capsules': typeof CapsulesIndexRoute
  '/session': typeof SessionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/campaign': typeof CampaignRoute
  '/capsules': typeof CapsulesRouteWithChildren
  '/circle': typeof CircleRoute
  '/decoy': typeof DecoyRoute
  '/dexter': typeof DexterRoute
  '/protocol': typeof ProtocolRoute
  '/triggers': typeof TriggersRoute
  '/verify': typeof VerifyRoute
  '/capsules/$id': typeof CapsulesIdRoute
  '/session/$id': typeof SessionIdRoute
  '/session/new': typeof SessionNewRoute
  '/capsules/': typeof CapsulesIndexRoute
  '/session/': typeof SessionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/campaign'
    | '/capsules'
    | '/circle'
    | '/decoy'
    | '/dexter'
    | '/protocol'
    | '/triggers'
    | '/verify'
    | '/capsules/$id'
    | '/session/$id'
    | '/session/new'
    | '/capsules/'
    | '/session/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/campaign'
    | '/circle'
    | '/decoy'
    | '/dexter'
    | '/protocol'
    | '/triggers'
    | '/verify'
    | '/capsules/$id'
    | '/session/$id'
    | '/session/new'
    | '/capsules'
    | '/session'
  id:
    | '__root__'
    | '/'
    | '/campaign'
    | '/capsules'
    | '/circle'
    | '/decoy'
    | '/dexter'
    | '/protocol'
    | '/triggers'
    | '/verify'
    | '/capsules/$id'
    | '/session/$id'
    | '/session/new'
    | '/capsules/'
    | '/session/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CampaignRoute: typeof CampaignRoute
  CapsulesRoute: typeof CapsulesRouteWithChildren
  CircleRoute: typeof CircleRoute
  DecoyRoute: typeof DecoyRoute
  DexterRoute: typeof DexterRoute
  ProtocolRoute: typeof ProtocolRoute
  TriggersRoute: typeof TriggersRoute
  VerifyRoute: typeof VerifyRoute
  SessionIdRoute: typeof SessionIdRoute
  SessionNewRoute: typeof SessionNewRoute
  SessionIndexRoute: typeof SessionIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaign': {
      id: '/campaign'
      path: '/campaign'
      fullPath: '/campaign'
      preLoaderRoute: typeof CampaignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capsules': {
      id: '/capsules'
      path: '/capsules'
      fullPath: '/capsules'
      preLoaderRoute: typeof CapsulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circle': {
      id: '/circle'
      path: '/circle'
      fullPath: '/circle'
      preLoaderRoute: typeof CircleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decoy': {
      id: '/decoy'
      path: '/decoy'
      fullPath: '/decoy'
      preLoaderRoute: typeof DecoyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dexter': {
      id: '/dexter'
      path: '/dexter'
      fullPath: '/dexter'
      preLoaderRoute: typeof DexterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protocol': {
      id: '/protocol'
      path: '/protocol'
      fullPath: '/protocol'
      preLoaderRoute: typeof ProtocolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/triggers': {
      id: '/triggers'
      path: '/triggers'
      fullPath: '/triggers'
      preLoaderRoute: typeof TriggersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capsules/': {
      id: '/capsules/'
      path: '/'
      fullPath: '/capsules/'
      preLoaderRoute: typeof CapsulesIndexRouteImport
      parentRoute: typeof CapsulesRoute
    }
    '/capsules/$id': {
      id: '/capsules/$id'
      path: '/$id'
      fullPath: '/capsules/$id'
      preLoaderRoute: typeof CapsulesIdRouteImport
      parentRoute: typeof CapsulesRoute
    }
    '/session/': {
      id: '/session/'
      path: '/session'
      fullPath: '/session/'
      preLoaderRoute: typeof SessionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$id': {
      id: '/session/$id'
      path: '/session/$id'
      fullPath: '/session/$id'
      preLoaderRoute: typeof SessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/new': {
      id: '/session/new'
      path: '/session/new'
      fullPath: '/session/new'
      preLoaderRoute: typeof SessionNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CapsulesRouteChildren {
  CapsulesIdRoute: typeof CapsulesIdRoute
  CapsulesIndexRoute: typeof CapsulesIndexRoute
}

const CapsulesRouteChildren: CapsulesRouteChildren = {
  CapsulesIdRoute: CapsulesIdRoute,
  CapsulesIndexRoute: CapsulesIndexRoute,
}

const CapsulesRouteWithChildren = CapsulesRoute._addFileChildren(
  CapsulesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CampaignRoute: CampaignRoute,
  CapsulesRoute: CapsulesRouteWithChildren,
  CircleRoute: CircleRoute,
  DecoyRoute: DecoyRoute,
  DexterRoute: DexterRoute,
  ProtocolRoute: ProtocolRoute,
  TriggersRoute: TriggersRoute,
  VerifyRoute: VerifyRoute,
  SessionIdRoute: SessionIdRoute,
  SessionNewRoute: SessionNewRoute,
  SessionIndexRoute: SessionIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
